# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce472abcbe62b3c3ca934960e8601ed11d7f429bf93da3c4bcf2da2ceaf24b7168ce89cef9f815eeecf50b3bdf5a272c42e6e019ae8c493b7d20248ec8c14816

test:
  secret_key_base: f8d1300e71d3075a0b2c20f5a337f31b8e543ffa745e38a5f4c968319b2fa4b5c332eaa05093f053cbf4c634d3f32481e77c6914d512b5dfa4f364da27128362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
